# Generated by Django 2.1.5 on 2019-04-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Balance',
            field=models.IntegerField(),
        ),
    ]
